version: 0.2
phases:
  build:
    commands:
      - echo "test build"
      - echo "add tag"
      - echo "commit1"
      - echo "commit2"
      - echo $COMMITID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - git tag -l --contains $COMMITID > test.txt
      - cat test.txt
      - printenv
      - codebuild-breakpoint
      - echo 'build completed'
