version: 0.2
phases:
  build:
    commands:
      - echo "test build"
      - echo $COMMITID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER

      - git tag -l --contains $COMMITID > test.txt
      - cat test.txt
      - printenv
      - codebuild-breakpoint
      - echo 'build completed'
